a=input("Enter 1st number : ")
b=input("Enter 2nd number : ")
print(a)
print(b)
print(a+b)
print(type(a))
print(type(b))

a=int(input("Enter 1st number : "))
b=int(input("Enter 2nd number : "))
print(a)
print(b)
print(a+b)
print(type(a))
print(type(b))